# Usa una imagen base de Node.js
FROM node:14

# Establece el directorio de trabajo
WORKDIR /usr/src/app

# Copia los archivos necesarios
COPY userapi/package*.json ./
COPY userapi/.env .
COPY userapi/user.js .

# Instala las dependencias
RUN npm install

# Expone el puerto
EXPOSE 3002

# Comando para iniciar la aplicación
CMD ["node", "user.js"]
